# Guide to all available configuration settings:
# - https://www.mkdocs.org/user-guide/configuration/
site_name: TinyBreaker Docs
repo_name: github-repo
repo_url: https://github.com/martin-rizzo/TinyBreakerDocs
edit_uri: ''
docs_dir: source
site_dir: docs

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Model Files: model-files.md
  - ComfyUI Nodes:
    - comfyui/empty-latent-image.md
    - Build Custom Transcoder: comfyui/build-custom-transcoder.md

extra_css:
  - css/custom.css

extra:
  disclaimer: "This documentation is for informational purposes only and may be subject to changes."

