site_name: TinyBreaker Documentation
repo_name: TinyBreaker Doc?
repo_url: https://github.com/martin-rizzo/TinyBreakerDocs
edit_uri: ''
github_pages:
  repo: https://github.com/martin-rizzo/TinyBreakerDocs

